// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abd.proto

package edu.sjsu.cs249.adb;

public final class Abd {
  private Abd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_NameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_NameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_Read1Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_Read1Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_Read1Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_Read1Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_Read2Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_Read2Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_AckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_AckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_adb_WriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_adb_WriteRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tabd.proto\022\003adb\032\033google/protobuf/empty." +
      "proto\"\007\n\005Empty\"\034\n\014NameResponse\022\014\n\004name\030\001" +
      " \001(\t\" \n\014Read1Request\022\020\n\010register\030\001 \001(\t\"1" +
      "\n\rRead1Response\022\021\n\ttimestamp\030\001 \001(\004\022\r\n\005va" +
      "lue\030\002 \001(\t\"B\n\014Read2Request\022\020\n\010register\030\001 " +
      "\001(\t\022\021\n\ttimestamp\030\002 \001(\004\022\r\n\005value\030\003 \001(\t\"\r\n" +
      "\013AckResponse\"C\n\014WriteRequest\022\020\n\010register" +
      "\030\001 \001(\t\022\022\n\ntimestampe\030\002 \001(\004\022\r\n\005value\030\003 \001(" +
      "\t2\313\001\n\nABDService\0221\n\004name\022\026.google.protob" +
      "uf.Empty\032\021.adb.NameResponse\022.\n\005read1\022\021.a" +
      "db.Read1Request\032\022.adb.Read1Response\022,\n\005r" +
      "ead2\022\021.adb.Read2Request\032\020.adb.AckRespons" +
      "e\022,\n\005write\022\021.adb.WriteRequest\032\020.adb.AckR" +
      "esponseB\026\n\022edu.sjsu.cs249.adbP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_adb_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_adb_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_adb_NameResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_adb_NameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_NameResponse_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_adb_Read1Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_adb_Read1Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_Read1Request_descriptor,
        new java.lang.String[] { "Register", });
    internal_static_adb_Read1Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_adb_Read1Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_Read1Response_descriptor,
        new java.lang.String[] { "Timestamp", "Value", });
    internal_static_adb_Read2Request_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_adb_Read2Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_Read2Request_descriptor,
        new java.lang.String[] { "Register", "Timestamp", "Value", });
    internal_static_adb_AckResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_adb_AckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_AckResponse_descriptor,
        new java.lang.String[] { });
    internal_static_adb_WriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_adb_WriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_adb_WriteRequest_descriptor,
        new java.lang.String[] { "Register", "Timestampe", "Value", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
