// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abd.proto

package edu.sjsu.cs249.adb;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.Empty)
    com.google.protobuf.MessageOrBuilder {
}
