// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abd.proto

package edu.sjsu.cs249.adb;

public interface NameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.NameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
