// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abd.proto

package edu.sjsu.cs249.adb;

public interface Read1ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.Read1Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 timestamp = 1;</code>
   */
  long getTimestamp();

  /**
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
