// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abd.proto

package edu.sjsu.cs249.adb;

public interface Read2RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.Read2Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string register = 1;</code>
   */
  java.lang.String getRegister();
  /**
   * <code>string register = 1;</code>
   */
  com.google.protobuf.ByteString
      getRegisterBytes();

  /**
   * <code>uint64 timestamp = 2;</code>
   */
  long getTimestamp();

  /**
   * <code>string value = 3;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 3;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
