// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: abd.proto

package edu.sjsu.cs249.adb;

public interface Read1RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:adb.Read1Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string register = 1;</code>
   */
  java.lang.String getRegister();
  /**
   * <code>string register = 1;</code>
   */
  com.google.protobuf.ByteString
      getRegisterBytes();
}
